   % process_Stereo_60and120

% population analysis for all cells recorded for Stereo_60and120 task;
% load .spk data generated by analysis_mc_Stereo_60and120_NF or analysis_Stereo_60and120_w_choice;
% generated by Jianbo on 4/14/16;

%% 1. Load data

clear all; close all;

%addpath('Z:\Jianbo\matlab\GUI_analysis')

% load .spk filelist
% cd C:\LabFolderNew\PlexonData\spklist
% cd C:\LabFolderNew\PlexonData\spklist\Disparity
%cd Z:\PlexonData\spklist\Disparity
cd P:\labFolderNew\Anjani\Disparity\bejirecording\spkfiles\dspbeh\good

display('pick a .spk filelist for the paradigm'); 
[fn, fnlen, num_of_files, fname] = load_spk_fname();        % fname is the filename of the list of data files

% cd C:\LabFolderNew\PlexonData\spkfile\Stereo60DS\Stereo2DFNear
%cd Z:\PlexonData\spkfile\Stereo60DS\Stereo2DFNear
cd P:\labFolderNew\Anjani\Disparity\bejirecording\spkfiles\dspbeh
%cd P:\labFolderNew\PlexonData\spkfile\Stereo60DS\Stereo2DFNear
dir_cdn = 24;
total_cdn = 120;
trial_ct = zeros(1,total_cdn);

%Greg's dataset
cd P:\labFolderNew\Anjani\matlab\anjani\Disparity\normalization
%dist=load("prefdspnormrespdist.mat");
dist=load("prefdspnormrespdist_prefdspfromtuningcurves.mat");

cd P:\labFolderNew\Anjani\Disparity\bejirecording\spkfiles\dspbeh
%load("Tuning-snlsupdated1spkfiles_benjiwdsptune.txt 53 0to600.mat")
%load("Tuning-snlsupdated1spkfiles_georgewdsptune.txt 38 0to600.mat")

%load('Tuning-snlsupdated1spkfiles_beh_georgeupdatedfinal56_behthres.txt 56 0to600.mat')


bANnc=LWAwpb_DS60_N_c(:,1)./LWAwpb_DS60_F_cc(:,1);
bAFnc=LWAwpb_DS60_F_cc(:,2)./LWAwpb_DS60_N_c(:,2);
bANncc=LWAwpb_DS60_N_cc(:,1)./LWAwpb_DS60_F_c(:,1);
bAFncc=LWAwpb_DS60_F_c(:,2)./LWAwpb_DS60_N_cc(:,2);

bANnc120=LWAwpb_DS120_N_c(:,1)./LWAwpb_DS120_F_cc(:,1);
bAFnc120=LWAwpb_DS120_F_cc(:,2)./LWAwpb_DS120_N_c(:,2);
bANncc120=LWAwpb_DS120_N_cc(:,1)./LWAwpb_DS120_F_c(:,1);
bAFncc120=LWAwpb_DS120_F_c(:,2)./LWAwpb_DS120_N_cc(:,2);

an=[bANnc;bANncc;bANnc120;bANncc120];
af=[bAFnc;bAFncc;bAFnc120;bAFncc120];
[p,x,y,x1,y1]=onesidedsigtest(an(an>0 & af>0 & an<10 &af<10),af(an>0 & af>0 & an<10 &af<10),'signrank');

figure
hold on
scatter([bANnc;bANncc;bANnc120;bANncc120],[bAFnc;bAFncc;bAFnc120;bAFncc120])
title(sprintf("mean x=%f mean y=%f p=%f",x,x1,p))
hold on
xlabel("wAn")
ylabel("wAf")
axis([0 3 0 3])

wnan=[LWAwpb_DS60_N_c(:,1);LWAwpb_DS60_N_cc(:,1);LWAwpb_DS120_N_c(:,1);LWAwpb_DS120_N_cc(:,1)];
wfan=[LWAwpb_DS60_N_c(:,2);LWAwpb_DS60_N_cc(:,2);LWAwpb_DS120_N_c(:,2);LWAwpb_DS120_N_cc(:,2)];

wnaf=[LWAwpb_DS60_F_cc(:,1);LWAwpb_DS60_F_c(:,1);LWAwpb_DS120_F_cc(:,1);LWAwpb_DS120_F_c(:,1)];
wfaf=[LWAwpb_DS60_F_cc(:,2);LWAwpb_DS60_F_c(:,2);LWAwpb_DS120_F_cc(:,2);LWAwpb_DS120_F_c(:,2)];

[p,x,y,x1,y1,a,b]=onesidedsigtest(wnan,wnaf,'signrank')  %wnan>wnaf
[p,x,y,x1,y1,a,b]=onesidedsigtest(wfan,wfaf,'signrank')

% wnan=[SNL_DS60_N_c(:,1);SNL_DS60_N_cc(:,1);SNL_DS120_N_c(:,1);SNL_DS120_N_cc(:,1)];
% wfan=[SNL_DS60_N_c(:,2);SNL_DS60_N_cc(:,2);SNL_DS120_N_c(:,2);SNL_DS120_N_cc(:,2)];
% 
% wnaf=[SNL_DS60_F_cc(:,1);SNL_DS60_F_c(:,1);SNL_DS120_F_cc(:,1);SNL_DS120_F_c(:,1)];
% wfaf=[SNL_DS60_F_cc(:,2);SNL_DS60_F_c(:,2);SNL_DS120_F_cc(:,2);SNL_DS120_F_c(:,2)];
% 
% [p,x,y,x1,y1]=onesidedsigtest(wnan,wnaf,'signrank')  %wnan>wnaf
% [p,x,y,x1,y1]=onesidedsigtest(wfan,wfaf,'signrank')
% 
figure
hold on
title("wn AN vs wn AF")
scatter(wnan,wnaf,'g')
hold on
scatter(wfan,wfaf,'b')
hold on
refline(1,0)


ind1=find(dist.prefdspvec<=1.6 & dist.prefdspvec>=-1.6);
prefdspvec=dist.prefdspvec(ind1);
normrespfar0p1=dist.normrespfar0p1(ind1);
normrespnear0p1=dist.normrespnear0p1(ind1);

[prefdspsort, ind]=sort(prefdspvec');
far0p1dist=normrespfar0p1(ind);
near0p1dist=normrespnear0p1(ind);

% load dsp tune fitting results for each monkey
cd P:\labFolderNew\Anjani\Disparity\bejirecording\spkfiles\dsptune
% %MT = load('resultsMT_Ringonewdata.mat');
% MT = load('resultsMT_benjifinaldata.mat');
% %MT = load('resultsMT_georgefinalbehdata.mat');

%MT = load('resultsMT_Ringonewdata.mat');
%MT = load('resultsMT_benjifinaldatanoflip.mat');
% MT = load('resultsMT_georgefinalbehdataupdated.mat');
%MT = load('resultsMT_georgefinalbehdata_new.mat');
%MT = load('resultsMT_benjifinaldataupdated_new.mat');

%MT=load('resultsMT_benjifinaldataupdated_new1');
MT=load('resultsMT_georgefinalbehdata_new_flip2.mat');

s1=near0p1dist;
s2=far0p1dist;
alphayesno="No";

% spline fit and direction interpolation;
p = 0.009;
dirstep = 1;     
DirInterp = [-180:dirstep:179];  


Dir =[-180:30:180];
Dir_c =[-150:30:210];
Dir_cc=[-210:30:150];

% DS60, cue Far
cond_D60_N_c =[7:12, 1:7];
cond_D60_N_cc=[19:24, 13:19];
% DS60, cue Near  
cond_D60_F_c =[55:60, 49:55];
cond_D60_F_cc=[67:72, 61:67];
% Ds1(whichneuron)20, cue Far
cond_D120_N_c =[31:36, 25:31];
cond_D120_N_cc=[43:48, 37:43];
% Ds1(whichneuron)20, cue Near  
cond_D120_F_c =[79:84, 73:79];
cond_D120_F_cc=[91:96, 85:91];

% single dir;
cond_sf = [103:108 97:103];
cond_sn = [115:120 109:115];
% DS60, single
cond_D60_sf_c = [102:108 97:102];
cond_D60_sf_cc = [104:108 97:104];
cond_D60_sn_c = [114:120 109:114];
cond_D60_sn_cc = [116:120 109:116];
% Ds1(whichneuron)20, single
cond_D120_sf_c = [101:108 97:101];
cond_D120_sf_cc = [105:108 97:105];
cond_D120_sn_c = [113:120 109:113];
cond_D120_sn_cc = [117:120 109:117];





window_start = 0;
window_end   = 600; %600 ms total




%% 2. Population averaging

for whichneuron = 1:num_of_files 


    a = load(fn(whichneuron,:));
    
    
    % get the mean firing rate, std and ste for all conditions
    [mean_r_raw, ste_r_raw, std_r_raw, spike_count,  block_num(whichneuron)] = ...
        rate_trial_ste_std(1, a, window_start, window_end);
    
    % just in case there is unfinished block trials
    if (length(find(a(:,3)==max(a(:,3))))*5>length(find(a(:,3)==max(a(:,3))-1)))
         block_num(whichneuron)=max(a(:,3));
    else
         block_num(whichneuron)=max(a(:,3))-1;
    end
    
    % deal with the fact that two paradigms have different total conditions
    mean_r(:, whichneuron) = mean_r_raw(1:total_cdn);
    ste_r(:, whichneuron) = ste_r_raw(1:total_cdn);
    std_r(:, whichneuron) = std_r_raw(1:total_cdn);
    for trialn=1: block_num(whichneuron),
        block_r(:,trialn,whichneuron) = spike_count(trialn,:);
    end
          
    whichneuron
    fn(whichneuron,:)
    mean_r(:, whichneuron) = mean_r_raw(1:total_cdn);
    ste_r(:, whichneuron) = ste_r_raw(1:total_cdn);
    std_r(:, whichneuron) = std_r_raw(1:total_cdn);
    

    
    R_sf_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_sf,whichneuron), p);
    R_sn_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_sn,whichneuron), p);
   
%     R_D60_sf_cc_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D60_sf_cc,whichneuron), p);
%     R_D60_sf_c_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D60_sf_c,whichneuron), p);
%     R_D60_sn_cc_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D60_sn_cc,whichneuron), p);
%     R_D60_sn_c_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D60_sn_c,whichneuron), p);


%     R_D120_sf_cc_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D120_sf_cc,whichneuron), p);
%     R_D120_sf_c_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D120_sf_c,whichneuron), p);
%     R_D120_sn_cc_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D120_sn_cc,whichneuron), p);
%     R_D120_sn_c_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D120_sn_c,whichneuron), p);

    R12_D60_F_cc_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D60_F_cc,whichneuron), p);
    R12_D60_F_c_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D60_F_c,whichneuron), p);
    R12_D60_N_cc_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D60_N_cc,whichneuron), p);
    R12_D60_N_c_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D60_N_c,whichneuron), p);

    R12_D120_F_cc_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D120_F_cc,whichneuron), p);
    R12_D120_F_c_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D120_F_c,whichneuron), p);
    R12_D120_N_cc_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D120_N_cc,whichneuron), p);
    R12_D120_N_c_SmoothDirTune(:,whichneuron) = csaps(Dir, mean_r(cond_D120_N_c,whichneuron), p);

    % get the value of pp format
    
    R_sf_pval(:, whichneuron) = ppval(R_sf_SmoothDirTune(:,whichneuron), DirInterp);
    R_sn_pval(:, whichneuron) = ppval(R_sn_SmoothDirTune(:,whichneuron), DirInterp);
    
%     R_D60_sf_c_norm_mean = ppval(R_D60_sf_cc_SmoothDirTune(:,whichneuron), DirInterp);   
%     R_D60_sf_c_norm_mean = ppval(R_D60_sf_c_SmoothDirTune(:,whichneuron), DirInterp);   
%     R_D60_sn_cc_norm_mean = ppval(R_D60_sn_cc_SmoothDirTune(:,whichneuron), DirInterp);   
%     R_D60_sn_c_norm_mean = ppval(R_D60_sn_c_SmoothDirTune(:,whichneuron), DirInterp);  

%     R_D120_sf_cc_norm_mean = ppval(R_D120_sf_cc_SmoothDirTune(:,whichneuron), DirInterp);   
%     R_D120_sf_c_norm_mean = ppval(R_D120_sf_c_SmoothDirTune(:,whichneuron), DirInterp);   
%     R_D120_sn_cc_norm_mean = ppval(R_D120_sn_cc_SmoothDirTune(:,whichneuron), DirInterp);   
%     R_D120_sn_c_norm_mean) = ppval(R_D120_sn_c_SmoothDirTune(:,whichneuron), DirInterp);  

    R_D60_F_cc_pval(:, whichneuron) = ppval(R12_D60_F_cc_SmoothDirTune(:,whichneuron), DirInterp);   
    R_D60_F_c_pval(:, whichneuron) = ppval(R12_D60_F_c_SmoothDirTune(:,whichneuron), DirInterp); 
    R_D60_N_cc_pval(:, whichneuron) = ppval(R12_D60_N_cc_SmoothDirTune(:,whichneuron), DirInterp);   
    R_D60_N_c_pval(:, whichneuron) = ppval(R12_D60_N_c_SmoothDirTune(:,whichneuron), DirInterp); 

    R_D120_F_cc_pval(:, whichneuron) = ppval(R12_D120_F_cc_SmoothDirTune(:,whichneuron), DirInterp);   
    R_D120_F_c_pval(:, whichneuron) = ppval(R12_D120_F_c_SmoothDirTune(:,whichneuron), DirInterp); 
    R_D120_N_cc_pval(:, whichneuron) = ppval(R12_D120_N_cc_SmoothDirTune(:,whichneuron), DirInterp);   
    R_D120_N_c_pval(:, whichneuron) = ppval(R12_D120_N_c_SmoothDirTune(:,whichneuron), DirInterp);
    
    % find peak & normalize for each single dir respnose tuning
    R_sf_PD(whichneuron) = DirInterp(find(R_sf_pval(:, whichneuron) == ...
        max(R_sf_pval(:, whichneuron))));
    R_sn_PD(whichneuron) = DirInterp(find(R_sn_pval(:, whichneuron) == ...
        max(R_sn_pval(:, whichneuron))));
    R_sf_norm(:, whichneuron)= R_sf_pval(:, whichneuron)/max(R_sf_pval(:, whichneuron));
    R_sn_norm(:, whichneuron)= R_sn_pval(:, whichneuron)/max(R_sn_pval(:, whichneuron));
    
    R_single_norm(:, whichneuron) = 0.5*(R_sf_norm(:, whichneuron)+ R_sn_norm(:, whichneuron));
    
    R_single_PD(whichneuron) = DirInterp(find(R_single_norm(:, whichneuron) == ...
        max(R_single_norm(:, whichneuron))));
    
    % align R_single_PD to VA0, then shift all tuning curves accordingly
    shift_to_deg = 0;
        
    DirInterp_NF_shift(:,whichneuron)      = DirInterp + shift_to_deg - ...
        R_single_PD(whichneuron); 
    DirInterp_D60_cc_shift(:,whichneuron)  = DirInterp -30 + shift_to_deg - ...
        R_single_PD(whichneuron); 
    DirInterp_D60_c_shift(:,whichneuron)   = DirInterp +30 + shift_to_deg - ...
        R_single_PD(whichneuron); 
    DirInterp_D120_cc_shift(:,whichneuron) = DirInterp -60 + shift_to_deg - ...
        R_single_PD(whichneuron); 
    DirInterp_D120_c_shift(:,whichneuron)  = DirInterp +60 + shift_to_deg - ...
        R_single_PD(whichneuron); 
       
    for i = 1:length(DirInterp_D60_cc_shift(:,whichneuron)),
     
     while DirInterp_NF_shift(i,whichneuron) > 180, 
        DirInterp_NF_shift(i,whichneuron) = DirInterp_NF_shift(i,whichneuron)-360;
     end;   
     while DirInterp_NF_shift(i,whichneuron) < -180,  
        DirInterp_NF_shift(i,whichneuron) = DirInterp_NF_shift(i,whichneuron)+360;
     end;
     
     while DirInterp_D60_cc_shift(i,whichneuron) > 180, 
        DirInterp_D60_cc_shift(i,whichneuron) = DirInterp_D60_cc_shift(i,whichneuron)-360;
     end;   
     while DirInterp_D60_cc_shift(i,whichneuron) < -180,  
        DirInterp_D60_cc_shift(i,whichneuron) = DirInterp_D60_cc_shift(i,whichneuron)+360;
     end;   
     
     while DirInterp_D60_c_shift(i,whichneuron) > 180, 
        DirInterp_D60_c_shift(i,whichneuron) = DirInterp_D60_c_shift(i,whichneuron)-360;
     end;   
     while DirInterp_D60_c_shift(i,whichneuron) < -180,  
        DirInterp_D60_c_shift(i,whichneuron) = DirInterp_D60_c_shift(i,whichneuron)+360;
     end;  
     
     while DirInterp_D120_cc_shift(i,whichneuron) > 180, 
        DirInterp_D120_cc_shift(i,whichneuron) = DirInterp_D120_cc_shift(i,whichneuron)-360;
     end;   
     while DirInterp_D120_cc_shift(i,whichneuron) < -180,  
        DirInterp_D120_cc_shift(i,whichneuron) = DirInterp_D120_cc_shift(i,whichneuron)+360;
     end;  
     
     while DirInterp_D120_c_shift(i,whichneuron) > 180, 
        DirInterp_D120_c_shift(i,whichneuron) = DirInterp_D120_c_shift(i,whichneuron)-360;
     end;   
     while DirInterp_D120_c_shift(i,whichneuron) < -180,  
        DirInterp_D120_c_shift(i,whichneuron) = DirInterp_D120_c_shift(i,whichneuron)+360;
     end;  
    end;
      
    [DirInterp_NF_shift(:,whichneuron),Idva_NF]           = sort(DirInterp_NF_shift(:,whichneuron)); 
    [DirInterp_D60_cc_shift(:,whichneuron),Idva_D60_cc]   = sort(DirInterp_D60_cc_shift(:,whichneuron)); 
    [DirInterp_D60_c_shift(:,whichneuron),Idva_D60_c]     = sort(DirInterp_D60_c_shift(:,whichneuron)); 
    [DirInterp_D120_cc_shift(:,whichneuron),Idva_D120_cc] = sort(DirInterp_D120_cc_shift(:,whichneuron)); 
    [DirInterp_D120_c_shift(:,whichneuron),Idva_D120_c]   = sort(DirInterp_D120_c_shift(:,whichneuron));
        
    R_D60_sf_cc_sort(:,whichneuron)  = R_sf_pval(Idva_D60_cc, whichneuron);
    R_D60_sf_c_sort(:,whichneuron)    = R_sf_pval(Idva_D60_c, whichneuron);
    R_D60_sn_cc_sort(:,whichneuron)  = R_sn_pval(Idva_D60_cc, whichneuron);
    R_D60_sn_c_sort(:,whichneuron)    = R_sn_pval(Idva_D60_c, whichneuron);
    
    R_D60_F_cc_sort(:,whichneuron)   = R_D60_F_cc_pval(Idva_NF, whichneuron);
    R_D60_F_c_sort(:,whichneuron)    = R_D60_F_c_pval(Idva_NF, whichneuron);
    R_D60_N_cc_sort(:,whichneuron)    = R_D60_N_cc_pval(Idva_NF, whichneuron);
    R_D60_N_c_sort(:,whichneuron)     = R_D60_N_c_pval(Idva_NF, whichneuron);
    
    R_D120_sf_cc_sort(:,whichneuron)  = R_sf_pval(Idva_D120_cc, whichneuron);
    R_D120_sf_c_sort(:,whichneuron)   = R_sf_pval(Idva_D120_c, whichneuron);
    R_D120_sn_cc_sort(:,whichneuron)  = R_sn_pval(Idva_D120_cc, whichneuron);
    R_D120_sn_c_sort(:,whichneuron)   = R_sn_pval(Idva_D120_c, whichneuron);
    
    R_D120_F_cc_sort(:,whichneuron)   = R_D120_F_cc_pval(Idva_NF, whichneuron);
    R_D120_F_c_sort(:,whichneuron)   = R_D120_F_c_pval(Idva_NF, whichneuron);
    R_D120_N_cc_sort(:,whichneuron)   = R_D120_N_cc_pval(Idva_NF, whichneuron);
    R_D120_N_c_sort(:,whichneuron)    = R_D120_N_c_pval(Idva_NF, whichneuron);
    
%     s1=sum(sum(R_D60_sn_c_sort))/size(R_D60_sn_c_sort,2);
%     s2=sum(sum(R_D60_sf_c_sort))/size(R_D60_sn_c_sort,2);
       
    % 1.2 model fit
    % Model 1
    % Y = w1*X1(:,1) + w2*X1(:,2)+w3
    % w1 is for near component, w2 is for far component;
    % DS60_N_c
    
    
    prefdsp=-MT.pre_dsp(whichneuron);
   
%    X = [R_D60_sn_c_sort(:,whichneuron), R_D60_sf_cc_sort(:,whichneuron)]; 
%    s2=sum(X(1:end-1,2));                    %excluding the repitition of 0 and 360 deg
%    s1=sum(X(1:end-1,1));   
     
%    X1= [vertcat(mean_r(cond_D60_sn_c(1:end-1),whichneuron),mean_r(cond_D60_sn_cc(1:end-1),whichneuron),mean_r(cond_D120_sn_c(1:end-1),whichneuron),mean_r(cond_D120_sn_cc(1:end-1),whichneuron)), vertcat(mean_r(cond_D60_sf_cc(1:end-1),whichneuron),mean_r(cond_D60_sf_c(1:end-1),whichneuron),mean_r(cond_D120_sf_cc(1:end-1),whichneuron),mean_r(cond_D120_sf_c(1:end-1),whichneuron))]; 
%    
%  %Lumping all conditions for Attend near    
%      Y = vertcat(mean_r(cond_D60_N_c(1:end-1),whichneuron),mean_r(cond_D60_N_cc(1:end-1),whichneuron),mean_r(cond_D120_N_c(1:end-1),whichneuron),mean_r(cond_D120_N_cc(1:end-1),whichneuron));
%    [param_AN(whichneuron,:),predAN(:,whichneuron),w_normAN(whichneuron,:), PV_normAN(whichneuron),Rsq_normAN(whichneuron)] = normlaizationwithfilter(X1,Y,alphayesno,s1,s2,prefdspsort,prefdsp);
% 
%    %Lumping all conditions for Attend far 
%    
%    %for beta condition the first col of X1 is the attended comp in the...
%    %normalization function
%     X1= [vertcat(mean_r(cond_D60_sf_cc(1:end-1),whichneuron),mean_r(cond_D60_sf_c(1:end-1),whichneuron),mean_r(cond_D120_sf_cc(1:end-1),whichneuron),mean_r(cond_D120_sf_c(1:end-1),whichneuron)),vertcat(mean_r(cond_D60_sn_c(1:end-1),whichneuron),mean_r(cond_D60_sn_cc(1:end-1),whichneuron),mean_r(cond_D120_sn_c(1:end-1),whichneuron),mean_r(cond_D120_sn_cc(1:end-1),whichneuron))]; 
%    Y = vertcat(mean_r(cond_D60_F_cc(1:end-1),whichneuron),mean_r(cond_D60_F_c(1:end-1),whichneuron),mean_r(cond_D120_F_cc(1:end-1),whichneuron),mean_r(cond_D120_F_c(1:end-1),whichneuron));
%    [param_AF(whichneuron,:),predAF(:,whichneuron),w_normAF(whichneuron,:), PV_normAF(whichneuron),Rsq_normAF(whichneuron)] = normlaizationwithfilter(X1,Y,alphayesno,s1,s2,prefdspsort,prefdsp);
%  

X1= [mean_r(cond_D60_sn_c(1:end-1),whichneuron),mean_r(cond_D60_sf_cc(1:end-1),whichneuron)];
  Y = mean_r(cond_D60_N_c(1:end-1),whichneuron);
   b=bANnc(whichneuron);  
   [param_60ANnc(whichneuron,:),pred60ANnc(:,whichneuron),w_norm60ANnc(whichneuron,:), PV_norm60ANnc(whichneuron),Rsq_norm60ANnc(whichneuron)] = normlaizationwithfilter(X1,Y,alphayesno,s1,s2,prefdspsort,prefdsp,b);

    X1=[mean_r(cond_D120_sn_c(1:end-1),whichneuron) mean_r(cond_D120_sf_cc(1:end-1),whichneuron)]; 
   Y=mean_r(cond_D120_N_c(1:end-1),whichneuron);
   b=bANnc120(whichneuron);
   [param_120ANnc(whichneuron,:),pred120ANnc(:,whichneuron),w_norm120ANnc(whichneuron,:), PV_norm120ANnc(whichneuron),Rsq_norm120ANnc(whichneuron)] = normlaizationwithfilter(X1,Y,alphayesno,s1,s2,prefdspsort,prefdsp,b); 

   
   
  X1= [mean_r(cond_D60_sn_c(1:end-1),whichneuron) mean_r(cond_D60_sf_cc(1:end-1),whichneuron)];
  Y = mean_r(cond_D60_F_cc(1:end-1),whichneuron);
   b=bAFnc(whichneuron);  
   [param_60AFnc(whichneuron,:),pred60AFnc(:,whichneuron),w_norm60AFnc(whichneuron,:), PV_norm60AFnc(whichneuron),Rsq_norm60AFnc(whichneuron)] = normlaizationwithfilter(flip(X1,2),Y,alphayesno,s2,s1,prefdspsort,prefdsp,b);

    X1=[mean_r(cond_D120_sn_c(1:end-1),whichneuron) mean_r(cond_D120_sf_cc(1:end-1),whichneuron)]; 
   Y=mean_r(cond_D120_F_cc(1:end-1),whichneuron);
   b=bAFnc120(whichneuron);
   [param_120AFnc(whichneuron,:),pred120AFnc(:,whichneuron),w_norm120AFnc(whichneuron,:), PV_norm120AFnc(whichneuron),Rsq_norm120AFnc(whichneuron)] = normlaizationwithfilter(flip(X1,2),Y,alphayesno,s2,s1,prefdspsort,prefdsp,b); 
   
   X1=[mean_r(cond_D60_sn_cc(1:end-1),whichneuron) ,mean_r(cond_D60_sf_c(1:end-1),whichneuron)];
   Y=mean_r(cond_D60_N_cc(1:end-1),whichneuron);
   b=bANncc(whichneuron);
   [param_60ANncc(whichneuron,:),pred60ANncc(:,whichneuron),w_norm60ANncc(whichneuron,:), PV_norm60ANncc(whichneuron),Rsq_norm60ANncc(whichneuron)] = normlaizationwithfilter(X1,Y,alphayesno,s1,s2,prefdspsort,prefdsp,b);
   
   X1=[mean_r(cond_D120_sn_cc(1:end-1),whichneuron),mean_r(cond_D120_sf_c(1:end-1),whichneuron)];
   Y=mean_r(cond_D120_N_cc(1:end-1),whichneuron);
   b=bANncc120(whichneuron);
  [param_120ANncc(whichneuron,:),pred120ANncc(:,whichneuron),w_norm120ANncc(whichneuron,:), PV_norm120ANncc(whichneuron),Rsq_norm120ANncc(whichneuron)] = normlaizationwithfilter(X1,Y,alphayesno,s1,s2,prefdspsort,prefdsp,b);
  
  
  
  X1=[mean_r(cond_D60_sn_cc(1:end-1),whichneuron) ,mean_r(cond_D60_sf_c(1:end-1),whichneuron)];
  Y=mean_r(cond_D60_F_c(1:end-1),whichneuron);
  b=bAFncc(whichneuron);
  [param_60AFncc(whichneuron,:),pred60AFncc(:,whichneuron),w_norm60AFncc(whichneuron,:), PV_norm60AFncc(whichneuron),Rsq_norm60AFncc(whichneuron)] = normlaizationwithfilter(flip(X1,2),Y,alphayesno,s2,s1,prefdspsort,prefdsp,b);

  X1=[mean_r(cond_D120_sn_cc(1:end-1),whichneuron) mean_r(cond_D120_sf_c(1:end-1),whichneuron)]; 
  Y=mean_r(cond_D120_F_c(1:end-1),whichneuron);
  b=bAFncc120(whichneuron);
  [param_120AFncc(whichneuron,:),pred120AFncc(:,whichneuron),w_norm120AFncc(whichneuron,:), PV_norm120AFncc(whichneuron),Rsq_norm120AFncc(whichneuron)] = normlaizationwithfilter(flip(X1,2),Y,alphayesno,s2,s1,prefdspsort,prefdsp,b); 

    
%     figure(2);
%     clf(2);
%     subplot(2,2,1)
%     errorbar(Dir, mean_r(cond_D60_N_c,whichneuron), ste_r(cond_D60_N_c,whichneuron),'ro');
%     hold on;
%     plot(Dir, mean_r(cond_D60_N_c,whichneuron),'r');
%     errorbar(Dir, mean_r(cond_D60_F_cc,whichneuron), ste_r(cond_D60_F_cc,whichneuron),'ko');     
%     
%     plot(Dir, mean_r(cond_D60_F_cc,whichneuron),'k');  
%     errorbar(Dir, mean_r(cond_D60_sf_cc,whichneuron), ste_r(cond_D60_sf_cc,whichneuron),'bo');     
% 
%     plot(Dir, mean_r(cond_D60_sf_cc,whichneuron),'b');    
%     errorbar(Dir, mean_r(cond_D60_sn_c,whichneuron), ste_r(cond_D60_sn_c,whichneuron),'go');     
% 
%     plot(Dir, mean_r(cond_D60_sn_c,whichneuron),'g');  
%     
%     
%   
% 
%     axis([-185  185   0    max(mean_r(:,whichneuron)) + 10]);
%                                  
%     xlabel ('DS60 (deg)');
%     ylabel ('Response (spks/s)');
%     plot(Dir,pred60ANnc([1:end 1],whichneuron) ,'r*-')
%      plot(Dir,pred60AFnc([1:end 1],whichneuron) ,'k*-')
%      %titlefn = sprintf('AN wnear=%f wfar=%f\n AF wnear=%f wfar=%f',w_normD60_N_c_sort(whichneuron,1),w_normD60_N_c_sort(whichneuron,2),w_normD60_F_cc_sort(whichneuron,1),w_normD60_F_cc_sort(whichneuron,2));   
%     title("D60NC"); 
%     
%     subplot(2,2,2)
%     errorbar(Dir, mean_r(cond_D60_N_cc,whichneuron), ste_r(cond_D60_N_cc,whichneuron),'ro');
%     hold on;
%     plot(Dir, mean_r(cond_D60_N_cc,whichneuron),'r');
%     errorbar(Dir, mean_r(cond_D60_F_c,whichneuron), ste_r(cond_D60_F_c,whichneuron),'ko');     
%     
%     plot(Dir, mean_r(cond_D60_F_c,whichneuron),'k');  
%     errorbar(Dir, mean_r(cond_D60_sn_cc,whichneuron), ste_r(cond_D60_sn_cc,whichneuron),'go');     
% 
%     plot(Dir, mean_r(cond_D60_sn_cc,whichneuron),'g');  
%     
%     errorbar(Dir, mean_r(cond_D60_sf_c,whichneuron), ste_r(cond_D60_sf_c,whichneuron),'bo');     
% 
%     plot(Dir, mean_r(cond_D60_sf_c,whichneuron),'b');    
%       
% 
%     axis([-185  185   0    max(mean_r(:,whichneuron)) + 10]);
%                                  
%     xlabel ('DS60 (deg)');
%     ylabel ('Response (spks/s)');
%   plot(Dir,pred60ANncc([1:end 1],whichneuron) ,'r*-')
%      plot(Dir,pred60AFncc([1:end 1],whichneuron) ,'k*-')
%      %titlefn = sprintf('AN wnear=%f wfar=%f\n AF wnear=%f wfar=%f',w_normD60_N_c_sort(whichneuron,1),w_normD60_N_c_sort(whichneuron,2),w_normD60_F_cc_sort(whichneuron,1),w_normD60_F_cc_sort(whichneuron,2));   
%     title("D60NCC"); 
%     
%     
%     subplot(2,2,3)
%     errorbar(Dir, mean_r(cond_D120_N_c,whichneuron), ste_r(cond_D120_N_c,whichneuron),'ro');
%     hold on;
%     plot(Dir, mean_r(cond_D120_N_c,whichneuron),'r');
%     errorbar(Dir, mean_r(cond_D120_F_cc,whichneuron), ste_r(cond_D120_F_cc,whichneuron),'ko');     
%     
%     plot(Dir, mean_r(cond_D120_F_cc,whichneuron),'k');  
%     errorbar(Dir, mean_r(cond_D120_sf_cc,whichneuron), ste_r(cond_D120_sf_cc,whichneuron),'bo');     
% 
%     plot(Dir, mean_r(cond_D120_sf_cc,whichneuron),'b');    
%     errorbar(Dir, mean_r(cond_D120_sn_c,whichneuron), ste_r(cond_D120_sn_c,whichneuron),'go');     
% 
%     plot(Dir, mean_r(cond_D120_sn_c,whichneuron),'g');   
%      
% 
%     axis([-185  185   0    max(mean_r(:,whichneuron)) + 10]);
%                                  
%     xlabel ('DS120 (deg)');
%     ylabel ('Response (spks/s)');
%     plot(Dir,pred120ANnc([1:end 1],whichneuron) ,'r*-')
%      plot(Dir,pred120AFnc([1:end 1],whichneuron) ,'k*-')
%      %titlefn = sprintf('AN wnear=%f wfar=%f\n AF wnear=%f wfar=%f',w_normD60_N_c_sort(whichneuron,1),w_normD60_N_c_sort(whichneuron,2),w_normD60_F_cc_sort(whichneuron,1),w_normD60_F_cc_sort(whichneuron,2));   
%     title("D120NC"); 
%     
%     subplot(2,2,4)
%     errorbar(Dir, mean_r(cond_D120_N_cc,whichneuron), ste_r(cond_D120_N_cc,whichneuron),'ro');
%     hold on;
%     plot(Dir, mean_r(cond_D120_N_cc,whichneuron),'r');
%     errorbar(Dir, mean_r(cond_D120_F_c,whichneuron), ste_r(cond_D120_F_c,whichneuron),'ko');     
%     
%     plot(Dir, mean_r(cond_D120_F_c,whichneuron),'k');  
%     errorbar(Dir, mean_r(cond_D120_sf_c,whichneuron), ste_r(cond_D120_sf_c,whichneuron),'bo');     
% 
%     plot(Dir, mean_r(cond_D120_sf_c,whichneuron),'b');    
%     errorbar(Dir, mean_r(cond_D120_sn_cc,whichneuron), ste_r(cond_D120_sn_cc,whichneuron),'go');     
% 
%     plot(Dir, mean_r(cond_D120_sn_cc,whichneuron),'g');  
%      
% 
%     axis([-185  185   0    max(mean_r(:,whichneuron)) + 10]);
%                                  
%     xlabel ('DS120 (deg)');
%     ylabel ('Response (spks/s)');
%    plot(Dir,pred120ANncc([1:end 1],whichneuron) ,'r*-')
%      plot(Dir,pred120AFncc([1:end 1],whichneuron) ,'k*-')
%      %titlefn = sprintf('AN wnear=%f wfar=%f\n AF wnear=%f wfar=%f',w_normD60_N_c_sort(whichneuron,1),w_normD60_N_c_sort(whichneuron,2),w_normD60_F_cc_sort(whichneuron,1),w_normD60_F_cc_sort(whichneuron,2));   
%     title("D120NCC"); 
% pause

end


%param evaluation
vcolnum=4;

Dsp_N=[];
Dsp_F=[];
for n = 1:length(MT.pre_dsp)
    if MT.pre_dsp(n)>=0
        Dsp_F=[Dsp_F n];
    else
        Dsp_N=[Dsp_N n];
    end
end

Dsp_N=[];
Dsp_F=[];
for i=1:num_of_files
% area_diff_60N_c(i)=(max( R_D60_sn_c_sort(:,i))-max( R_D60_sf_cc_sort(:,i)))/(max( R_D60_sn_c_sort(:,i))+max( R_D60_sf_cc_sort(:,i)));
% area_diff_60N_cc(i)=(max( R_D60_sn_cc_sort(:,i))-max( R_D60_sf_c_sort(:,i)))/(max( R_D60_sn_cc_sort(:,i))+max( R_D60_sf_c_sort(:,i)));
area_diff_60N_c(i)=(max( mean_r(cond_D60_sn_c,i))-max( mean_r(cond_D60_sf_c,i)))/(max( mean_r(cond_D60_sn_c,i))+max( mean_r(cond_D60_sf_c,i)));
 if area_diff_60N_c(i)>0
        Dsp_N=[Dsp_N i];
    else
        Dsp_F=[Dsp_F i];
 end
end

figure
scatter([PV_norm60ANnc(Dsp_N),PV_norm60ANncc(Dsp_N),PV_norm120ANnc(Dsp_N),PV_norm120ANncc(Dsp_N)],[PV_norm60AFnc(Dsp_N),PV_norm60AFncc(Dsp_N),PV_norm120AFnc(Dsp_N),PV_norm120AFncc(Dsp_N)],'g')
hold on
scatter([PV_norm60ANnc(Dsp_F),PV_norm60ANncc(Dsp_F),PV_norm120ANnc(Dsp_F),PV_norm120ANncc(Dsp_F)],[PV_norm60AFnc(Dsp_F),PV_norm60AFncc(Dsp_F),PV_norm120AFnc(Dsp_F),PV_norm120AFncc(Dsp_F)],'b')
hold on
xlabel("PV Attend near")
ylabel("PV Attend far")
axis([10 100 10 100])



figure
scatter([param_60ANnc(Dsp_N,vcolnum);param_60ANncc(Dsp_N,vcolnum);param_120ANnc(Dsp_N,vcolnum);param_120ANncc(Dsp_N,vcolnum)],[param_60AFnc(Dsp_N,vcolnum);param_60AFncc(Dsp_N,vcolnum);param_120AFnc(Dsp_N,vcolnum);param_120AFncc(Dsp_N,vcolnum)],'g')
hold on
scatter([param_60ANnc(Dsp_F,vcolnum);param_60ANncc(Dsp_F,vcolnum);param_120ANnc(Dsp_F,vcolnum);param_120ANncc(Dsp_F,vcolnum)],[param_60AFnc(Dsp_F,vcolnum);param_60AFncc(Dsp_F,vcolnum);param_120AFnc(Dsp_F,vcolnum);param_120AFncc(Dsp_F,vcolnum)],'b')
hold on
xlabel("v param Attend near")
ylabel("v param Attend far")

% betacolnum=5;
% 
% figure
% scatter([param_60ANnc(Dsp_N,betacolnum);param_60ANncc(Dsp_N,betacolnum);param_120ANnc(Dsp_N,betacolnum);param_120ANncc(Dsp_N,betacolnum)],[param_60AFnc(Dsp_N,betacolnum);param_60AFncc(Dsp_N,betacolnum);param_120AFnc(Dsp_N,betacolnum);param_120AFncc(Dsp_N,betacolnum)],'g')
% hold on
% scatter([param_60ANnc(Dsp_F,betacolnum);param_60ANncc(Dsp_F,betacolnum);param_120ANnc(Dsp_F,betacolnum);param_120ANncc(Dsp_F,betacolnum)],[param_60AFnc(Dsp_F,betacolnum);param_60AFncc(Dsp_F,betacolnum);param_120AFnc(Dsp_F,betacolnum);param_120AFncc(Dsp_F,betacolnum)],'b')
% hold on
% xlabel("beta param Attend near")
% ylabel("beta param Attend far")

% [p,x,y,x1,y1]=onesidedsigtest([param_60ANnc(Dsp_N,betacolnum);param_60ANncc(Dsp_N,betacolnum);param_120ANnc(Dsp_N,betacolnum);param_120ANncc(Dsp_N,betacolnum)],[param_60AFnc(Dsp_N,betacolnum);param_60AFncc(Dsp_N,betacolnum);param_120AFnc(Dsp_N,betacolnum);param_120AFncc(Dsp_N,betacolnum)],'signrank')
% 
% [p,x,y,x1,y1]=onesidedsigtest([param_60ANnc(Dsp_F,betacolnum);param_60ANncc(Dsp_F,betacolnum);param_120ANnc(Dsp_F,betacolnum);param_120ANncc(Dsp_F,betacolnum)],[param_60AFnc(Dsp_F,betacolnum);param_60AFncc(Dsp_F,betacolnum);param_120AFnc(Dsp_F,betacolnum);param_120AFncc(Dsp_F,betacolnum)],'signrank')







vAN_near=[param_60ANnc(Dsp_N,vcolnum);param_60ANncc(Dsp_N,vcolnum);param_120ANnc(Dsp_N,vcolnum);param_120ANncc(Dsp_N,vcolnum)];
vAF_near=[param_60AFnc(Dsp_N,vcolnum);param_60AFncc(Dsp_N,vcolnum);param_120AFnc(Dsp_N,vcolnum);param_120AFncc(Dsp_N,vcolnum)];
vAN_far=[param_60ANnc(Dsp_F,vcolnum);param_60ANncc(Dsp_F,vcolnum);param_120ANnc(Dsp_F,vcolnum);param_120ANncc(Dsp_F,vcolnum)];
vAF_far=[param_60AFnc(Dsp_F,vcolnum);param_60AFncc(Dsp_F,vcolnum);param_120AFnc(Dsp_F,vcolnum);param_120AFncc(Dsp_F,vcolnum)];

x1=median(vAN_near)
x2=median(vAF_near)
x3=median(vAN_far)
x4=median(vAF_far)

distv=[vAN_near;vAF_near;vAN_far;vAF_far];

total_unit_num = num_of_files ;

mean(MT.pre_dsp(Dsp_N))
mean(MT.pre_dsp(Dsp_F))


figure
histogram(MT.pre_dsp(Dsp_N))
hold on
histogram(MT.pre_dsp(Dsp_F))


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% save a .mat file
%cd Z:\PlexonData\datafile\Disparity
MatlabFileName = sprintf('basicNormwithgausfiltervforindividualneuronfinal_new-dspbeh%s %d %dto%d.mat',fname,num_of_files,window_start,window_end); 
save(MatlabFileName);

dist_benji=[    0.0686
   14.6601
    5.4542
    0.0259
    1.3841
    1.9167
    1.7959
    0.0398
    0.5002
   15.0000
    2.0756
    0.0405
   15.0000
    0.9688
    7.0388
    6.3601
    6.2303
   15.0000
    2.7858
   15.0000
    0.0445
    7.5517
    5.0205
    4.7811
    0.0053
    1.2116
    0.0445
    0.1250
   15.0000
    7.3139
    0.0279
    0.5206
    6.9024
    0.4828
   15.0000
    0.0414
    5.1895
    7.0289
    0.1188
   15.0000
    0.8050
   15.0000
    0.2434
   15.0000
    7.1155
    9.2063
   15.0000
    0.0445
    0.0804
   10.8603
   15.0000
    0.1844
    0.3067
    0.0445
    0.1231
    3.5203
    0.9983
    0.0789
    1.3041
    4.4481
    0.1101
   15.0000
    0.3687
    8.1869
    5.2809
    0.0748
   15.0000
    0.3070
   15.0000
   12.3976
   14.9999
    6.9670
    2.8708
    2.2105
    0.0445
    1.0771
    3.8977
    7.5001
    0.0023
    1.2941
   15.0000
    0.0967
    6.0369
    0.8110
    0.0472
    1.4187
    1.4418
    1.9439
    0.0695
   15.0000
   13.1842
    6.0372
    0.0708
   15.0000
    0.7358
    1.2924
    0.0445
   15.0000
   14.9999
    9.1988
    6.5157
    0.0445
    0.0194
    7.0674
    9.0856
    0.0055
    0.3076
    0.0445
    0.1048
    9.0670
    5.1309
    0.0279
    1.2653
    1.6673
    0.0994
   15.0000
    0.0034
   15.0000
    4.4863
    3.6199
   15.0000
    0.9608
    7.5286
    5.2354
   15.0000
   15.0000
    2.8799
   15.0000
    0.0445
   15.0000
   15.0000
    7.1241
    0.0052
    1.2434
    0.0445
    0.1210
   15.0000
    8.2789
    0.0128
    9.0297
    6.9801
    0.4828
    0.1055
    0.2659
    3.7021
   11.6834
    0.0727
   15.0000
    0.0402
   15.0000
    0.4360
   11.4907
    8.2990
    4.6256
   15.0000
    0.0445
    0.1706
   15.0000
    7.9717
    0.0051
    2.2171
    0.0445
    0.0768
    3.5409
    0.8784
    0.0597
    1.3558
    1.4531
    0.0493
    0.0474
    0.0490
    6.4989
    2.3508
    0.0479
   15.0000
    0.8968
   15.0000
   12.2906
   14.9999
    9.3361
    7.2209
    0.5047
    0.0068
    1.0311
    6.4067
   11.0712
    0.0055
    0.0011
   14.9999
    0.0909
    8.2990
    0.7150
    0.0281
    1.4169
   14.0175
    0.2669
   15.0000
    8.3729
    1.6245
    5.7630
    0.0650
   15.0000
    0.7362
    0.0320
    0.3970
   15.0000
   15.0000
   10.8293
    7.8030
    0.0445
    0.0208
    8.5030
    6.7432
    0.0055
    1.3999
    0.0445
    1.8134
    4.2072
    5.4080
    5.7360
    7.5578
    8.9513
    9.6514
    7.6902
    0.0691
    0.8752
    0.0031
    0.1321
    0.3811
    9.3018
   14.9599
    4.3942
    4.3292
    1.0729
    0.3454
    0.0445
   13.2303
    7.9349
    3.5028
    1.7713
    7.4876
    2.9664
    7.9349
    0.0027
    8.6966
    0.4549
   14.6069
    2.3861
   12.5868
   12.0130
    6.3271
    0.0388
    6.9991
    7.7127
    0.2710
    7.1878
    7.4992
    5.9997
    3.3750
   10.0904
   14.8447
    0.0445
    3.6044
    0.1173
    7.2933
    2.8275
    7.5443
    7.6764
    3.5986
    4.3286
    1.4523
    0.7872
   14.3663
    8.0191
    8.3919
    3.1107
    2.1891
   13.1463
    7.4682
    3.2234
    0.3528
   12.0833
   13.5002
    7.2808
    0.8810
    6.0847
    0.2865
    0.0069
    0.1849
    7.8670
   10.3177
    3.2432
    1.9607
    4.0178
    3.3826
    4.6605
    1.1203
    0.4655
   14.7223
    4.5581
    0.4848
    2.6131
    1.8947
    4.9210
    7.5496
    9.3749
    0.0072
   13.4910
    7.1109
    6.6415
    3.9828
    7.9164
    0.3107
   15.0000
    5.9112
    7.9149
    7.5173
    4.4002
    8.9083
    6.3099
    2.7476
    4.4722
    5.2846
    7.8177
    2.5968
    4.9040
   10.8484
    2.4842
    7.5804
    1.9115
    6.7161
    4.1620
    0.3766
    6.2188
    8.4943
    4.9859
    3.9168
    0.6252
    0.3495
    0.0445
    0.1571
    0.0809
    7.3103
    3.2145
    8.1318
    7.7881
    7.2160
    5.3104
    4.3983
    0.1726
    5.4530
    0.9295
    8.9097
    8.1411
    4.7158
    4.8633
    7.3182
    2.4648
    0.0218
    7.1533
    7.6026
   13.8487
    3.7875
    6.7588
    0.3511
    0.0069
    8.9561
    7.8822
    7.5044
    2.8922
    7.3909
    3.2425
    3.3951
    4.8737
    0.4291
    0.3307
   14.3732
    8.0024
    8.5369
    2.5532
    2.1950
    0.9818
    6.8150
    4.9161
    0.3420
   12.0402
   14.8212
    6.9323
    1.0435
    4.7975
    0.3714
    0.0442
    0.1397
    0.0612
   10.1008
    3.9001
    8.6813
    5.8225
    3.2704
    5.8072
   10.4130
    0.3459
   14.6849
    5.0065
    0.2603
    2.6072
    3.0928
   13.6702
    7.6882
    2.0886
    0.0074
   14.1497
    6.9816
    7.1730
    4.1448
    9.3338
    0.3670
   15.0000
    0.1515
    0.1048
    3.4024
    3.5799
    0.2394
    5.8927];



figure
histogram(dist_benji)
hold on
histogram(distv)
ranksum(dist_benji,distv)

median(dist_benji)
median(distv)



figure
histogram(dist_benji(end/2+1:end))
hold on
histogram(distv(end/2+1:end))
ranksum(dist_benji(end/2+1:end),distv(end/2+1:end))

median(dist_benji(end/2+1:end))



median(distv(end/2+1:end))


figure
histogram(dist_benji(1:end/2))
hold on
histogram(distv(1:end/2))
ranksum(dist_benji(1:end/2),distv(1:end/2))

median(dist_benji(1:end/2))



median(distv(1:end/2))





